### ISSUE TITLE
consider using a package for KL

### ISSUE THREAD

**Issue by mcfrank** [mcfrank/looking_time_models#6]
currently we don't check numerics or inputs for the `kl_div` function

**Comment by GalRaz** [comment]
built-in package give weird answers. doing by hand but with input checking, especially accounting for what to do with 0's

**Comment by GalRaz** [comment]
just realized we shuold check if we're doing KL in log space, and whether that matters.

**Comment by anjiecao** [comment]
currently checking hand-implemented version of KL with this prepackaged version: https://cran.r-project.org/web/packages/philentropy/vignettes/Information_Theory.html

maybe should swap?
